# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: link_status.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='link_status.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\x11link_status.proto\"<\n\nLinkStatus\x12\x0e\n\x06node_1\x18\x01 \x02(\t\x12\x0e\n\x06node_2\x18\x02 \x02(\t\x12\x0e\n\x06status\x18\x03 \x02(\t'
)




_LINKSTATUS = _descriptor.Descriptor(
  name='LinkStatus',
  full_name='LinkStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_1', full_name='LinkStatus.node_1', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node_2', full_name='LinkStatus.node_2', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='LinkStatus.status', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['LinkStatus'] = _LINKSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LinkStatus = _reflection.GeneratedProtocolMessageType('LinkStatus', (_message.Message,), {
  'DESCRIPTOR' : _LINKSTATUS,
  '__module__' : 'link_status_pb2'
  # @@protoc_insertion_point(class_scope:LinkStatus)
  })
_sym_db.RegisterMessage(LinkStatus)


# @@protoc_insertion_point(module_scope)
